apiVersion: v1
kind: Service
metadata:
    name: webserver-svc
    namespace: web
spec:
    type: NodePort
    selector:
        app: web
        tag: test
    ports:
    -   name: ws-port
        protocol: TCP
        port: 8501
        nodePort: 30000
        targetPort: ws-c-port
